backend:
  name: github
  repo: kalungwemwenshi-alt/tdetes 
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  auth_scope: repo

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
