backend:
  name: git-gateway
  branch: main  # or 'master' depending on your repo name

media_folder: "assets/uploads" # Where uploaded images go in your repo
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
      - label: "About Page"
        name: "about"
        file: "about.html"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
